import streamlit as st

st.write('Hello world')
st.write('Hello world 2.0')
st.write('Hola Monono..!!')

st.button('Hit me')
#st.data_editor('Edit data', data)
st.checkbox('Check me out')
st.radio('Pick one:', ['nose','ear'])
st.selectbox('Select', [1,2,3])
st.multiselect('Multiselect', [1,2,3])
st.slider('Slide me', min_value=0, max_value=50)
st.select_slider('Slide to select', options=[1,'2','3','4'])
st.text_input('Introduce algun texto')
st.number_input('Escribe un numero')
st.text_area('Area for textual entry')
st.date_input('Date input')
st.time_input('Time entry')
st.file_uploader('Cargar un archivo')
#st.download_button('On the dl', data)
